{% set name = "perl-file-remove" %}
{% set version = "1.61" %}
{% set sha256 = "fd857f585908fc503461b9e48b3c8594e6535766bc14beb17c90ba58d5dc4975" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/File-Remove-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # nothing provides perl >=5.32.1,<6.0a0 *_perl5 needed by perl-extutils-makemaker-7.36-pl5321hd8ed1ab_0
  skip: true  # [win]
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-pathtools    # for File::Spec
    - perl-test-simple  # for Test::More
  run:
    - perl
    - perl-pathtools    # for File::Spec
    - perl-test-simple  # for Test::More

test:
  imports:
    - File::Remove

about:
  home: http://metacpan.org/pod/File::Remove
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: Remove files and directories
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
